import type { Part } from './types';

export const parts: Part[] = [
  {
    id: 'part-001',
    name: 'All-Terrain Tire Set',
    description: 'A set of four durable tires designed for off-road desert conditions. Excellent grip and longevity.',
    price: 899.99,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '123 Dune Way, Sandville, AZ',
  },
  {
    id: 'part-002',
    name: 'Heavy-Duty Radiator',
    description: 'High-performance radiator to keep your engine cool under the scorching desert sun.',
    price: 349.50,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '456 Oasis Blvd, Rock Springs, NV',
  },
  {
    id: 'part-003',
    name: 'Performance Air Filter',
    description: 'Protects your engine from sand and dust while improving airflow and horsepower.',
    price: 75.00,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: false,
    vendorAddress: '123 Dune Way, Sandville, AZ',
  },
  {
    id: 'part-004',
    name: 'LED Light Bar',
    description: '22-inch light bar for superior visibility during night-time desert drives.',
    price: 199.99,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '789 Canyon Rd, Mirage City, CA',
  },
  {
    id: 'part-005',
    name: 'Premium Ceramic Brake Pads',
    description: 'Low-dust, quiet operation brake pads with excellent stopping power for any vehicle.',
    price: 120.75,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '456 Oasis Blvd, Rock Springs, NV',
  },
  {
    id: 'part-006',
    name: 'Upgraded Suspension Kit',
    description: 'Provides a smoother ride on rough terrain and increases ground clearance.',
    price: 1250.00,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '789 Canyon Rd, Mirage City, CA',
  },
  {
    id: 'part-007',
    name: 'Engine Oil - Synthetic Blend',
    description: 'High-mileage synthetic blend oil for superior engine protection in extreme temperatures.',
    price: 45.99,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '123 Dune Way, Sandville, AZ',
  },
  {
    id: 'part-008',
    name: 'Car Battery - 750 CCA',
    description: 'Reliable car battery with 750 cold cranking amps for consistent starts in all weather.',
    price: 180.00,
    imageUrl: 'https://placehold.co/600x400.png',
    inStock: true,
    vendorAddress: '456 Oasis Blvd, Rock Springs, NV',
  },
];
